-- Lectorbook Supabase schema
-- Execute este ficheiro no SQL Editor do Supabase.

create extension if not exists vector;
create extension if not exists pgcrypto;

-- =========================
-- 1) RAG: documentos vetoriais
-- =========================
create table if not exists public.documents (
  id bigserial primary key,
  content text,
  metadata jsonb,
  embedding vector(768)
);

create index if not exists documents_metadata_gin_idx
  on public.documents using gin (metadata);

create index if not exists documents_embedding_ivfflat_idx
  on public.documents using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create or replace function public.match_documents (
  query_embedding vector(768),
  match_count int default 8,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql
stable
as $$
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.documents d
  where d.metadata @> filter
  order by d.embedding <=> query_embedding
  limit greatest(match_count, 1);
$$;

-- =========================
-- 2) Histórico de chat
-- =========================
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id text not null,
  message jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_session_created_idx
  on public.chat_messages (session_id, created_at);

-- =========================
-- 3) Sistema de alunos
-- =========================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'student_level') then
    create type public.student_level as enum ('bronze', 'prata', 'ouro', 'epico', 'lendario');
  end if;
end
$$;

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  session_key text not null unique,
  access_code text unique,
  name text not null,
  email text,
  class text,
  course text not null default 'Contabilidade',
  gender text check (gender in ('M', 'F')),
  total_xp integer not null default 0 check (total_xp >= 0),
  level public.student_level not null default 'bronze',
  quizzes_completed integer not null default 0 check (quizzes_completed >= 0),
  avg_percentage numeric(5,2) not null default 0 check (avg_percentage >= 0 and avg_percentage <= 100),
  modules_studied integer not null default 0 check (modules_studied >= 0),
  study_streak integer not null default 0 check (study_streak >= 0),
  last_study_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_results (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  repo_full_name text,
  score integer not null check (score >= 0),
  total_questions integer not null check (total_questions > 0),
  percentage numeric(5,2) not null check (percentage >= 0 and percentage <= 100),
  xp_earned integer not null check (xp_earned >= 0),
  level_before public.student_level not null,
  level_after public.student_level not null,
  created_at timestamptz not null default now()
);

create index if not exists quiz_results_student_id_created_idx
  on public.quiz_results (student_id, created_at desc);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  repo_full_name text,
  started_at timestamptz not null default now()
);

create index if not exists study_sessions_student_id_started_idx
  on public.study_sessions (student_id, started_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_students_set_updated_at on public.students;
create trigger trg_students_set_updated_at
before update on public.students
for each row execute function public.set_updated_at();

create or replace view public.student_ranking as
select
  s.id,
  s.name,
  s.class,
  s.gender,
  s.total_xp,
  s.level,
  s.quizzes_completed,
  s.avg_percentage,
  s.last_study_at,
  rank() over (
    order by s.total_xp desc, s.avg_percentage desc, s.quizzes_completed desc, s.created_at asc
  ) as rank_position
from public.students s;


alter table public.students add column if not exists access_code text;
alter table public.students add column if not exists email text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'access_code'
  ) then
    execute 'create unique index if not exists students_access_code_unique_idx on public.students(access_code) where access_code is not null';
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'students'
      and column_name = 'email'
  ) then
    execute 'create unique index if not exists students_email_unique_idx on public.students(lower(email)) where email is not null';
  end if;
end
$$;
